spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/takeout?characterEncoding=utf8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell
  port: 8090
logging:
  pattern:
    console: "%d - %msg%n"
  path: D:/IdeaProjects/sell/logs

